FROM phusion/baseimage:0.9.17
RUN apt-get update
RUN apt-get install -y \
                        libboost1.54-all-dev \
                        curl \
                        wget \
                        libtool \
                        libiberty-dev \
                        libbz2-dev \
                        libgnutls-dev \
                        libevent-dev \
                        libdouble-conversion-dev \
                        libgoogle-glog-dev \
                        libgflags-dev \
                        liblz4-dev \
                        liblzma-dev \
                        libsnappy-dev \
                        zlib1g-dev \
                        binutils-dev \
                        libjemalloc-dev \
                        libssl-dev \
                        libkrb5-dev \
                        libsasl2-dev \
                        libnuma-dev \
                        pkg-config \
