#!/bin/sh
#
# relevanced  Start/Stop the relevanced daemon.
#
# chkconfig: 345 90 60
# Description:
#  relevanced is a fast text similarity-scoring server
#  with persistent document centroids.
#
### BEGIN INIT INFO
# Provides: relevanced
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start:  345
# Default-Stop: 90
# Short-Description: run relevanced daemon
# Description:
#  relevanced is a fast text similarity-scoring server
#  with persistent document centroids.
#
### END INIT INFO

if [ -z $RETVAL ]; then RETVAL=0; fi
if [ -z $PROG ]; then PROG="relevanced"; fi
if [ -z $EXEC ]; then EXEC=/usr/bin/relevanced; fi
if [ -z $REAL_CONFIG_PATH ]; then REAL_CONFIG_PATH=/etc/relevanced/relevanced.json; fi
if [ -z $LOCKFILE ]; then LOCKFILE=/var/lock/relevanced; fi
if [ -z $UID ]; then UID=$(id -u); fi

if [ $UID -eq 0 ] && [ -e /etc/sysconfig/$PROG ]; then
  . /etc/sysconfig/$PROG
fi

if [ -e /etc/init.d/functions ]; then
  . /etc/init.d/functions
fi

set -e

if [ ! -e $FLAGS_PATH ] && [ ! -e $REAL_CONFIG_PATH ]; then
  echo "No config file found at $REAL_CONFIG_PATH"
  exit 1
fi

case "$1" in
  start)
    echo -n "Starting $PROG: "
    ARGS=""

    if [ -e $REAL_CONFIG_PATH ]; then ARGS="$ARGS --config_file=$REAL_CONFIG_PATH"; fi

    daemon $PROG --name relevanced -u relevanced:relevanced -- $ARGS
    exit $?
    ;;

  stop)
    echo -n "Stopping $PROG: "
    daemon --stop --name relevanced -u relevanced:relevanced -- $ARGS
    RETVAL=$?
    sleep 1
    exit $RETVAL
    ;;

  restart)
    ${0} stop
    ${0} start
    ;;

  status)
    echo -n "$PROG is "
    if daemon --running --name relevanced -u relevanced:relevanced; then
      echo "running"
    else
      echo "not running."
      exit 1
    fi
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
