#!/bin/sh
#
# relevanced  Start/Stop the relevanced daemon.
#
# chkconfig: 345 90 60
# Description:
#  relevanced is a fast text similarity-scoring server
#  with persistent document centroids.
#
### BEGIN INIT INFO
# Provides: relevanced
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start:  345
# Default-Stop: 90
# Short-Description: run relevanced daemon
# Description:
#  relevanced is a fast text similarity-scoring server
#  with persistent document centroids.
#
### END INIT INFO

if [ -z $RETVAL ]; then RETVAL=0; fi
if [ -z $PROG ]; then PROG="relevanced"; fi
if [ -z $EXEC ]; then EXEC=/usr/bin/relevanced; fi
if [ -z $REAL_CONFIG_PATH ]; then REAL_CONFIG_PATH=/etc/relevanced/relevanced.json; fi
if [ -z $LOCKFILE ]; then LOCKFILE=/var/lock/relevanced; fi
if [ -z $UID ]; then UID=$(id -u); fi

if [ $UID -eq 0 ] && [ -e /etc/sysconfig/$PROG ]; then
  . /etc/sysconfig/$PROG
fi

if [ -e /etc/init.d/functions ]; then
  . /etc/init.d/functions
fi

if [ ! -e $FLAGS_PATH ] && [ ! -e $REAL_CONFIG_PATH ]; then
  echo "No config file found at $REAL_CONFIG_PATH"
  RETVAL=1
fi

ensure_root() {
  if [ $UID -ne 0 ] ; then
    echo "User has insufficient privilege."
    RETVAL=1
  fi
}

start() {
  ensure_root

  ARGS=""

  if [ -e $REAL_CONFIG_PATH ]; then ARGS="$ARGS --config_file=$REAL_CONFIG_PATH"; fi

  daemon $PROG --name relevanced -- $ARGS
  RETVAL=$?
}

stop() {
  ensure_root
  daemon --stop --name relevanced
}

restart() {
  stop
  $(sleep 3)
  start
}

status() {
  ensure_root
  if daemon --running --name relevanced; then
    echo "$PROG is running."
    RETVAL=0
  else
    echo "$PROG is not running."
    RETVAL=7
  fi
}

usage() {
  echo "Usage: $0 {start|stop|status|restart}"
  RETVAL=2
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) restart ;;
    status) status ;;
    *) usage ;;
esac

exit ${RETVAL}
