#!/bin/sh

set -e

# shamelessly stolen from redis

if [ "$1" = "purge" ]
then
    rm -rf /var/lib/relevanced
    userdel relevanced
fi

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
    systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

