#!/bin/sh

set -eu

# shamelessly stolen from redis

USER="relevanced"
GROUP="$USER"

chown $USER:$GROUP /var/lib/relevanced
chown $USER:$GROUP /var/log/relevanced

# Automatically added by dh_installinit
if [ -x "/etc/init.d/relevanced" ]; then
    invoke-rc.d relevanced start || exit $?
fi
# End automatically added section

