#!/bin/sh
set -e

#shamelessly stolen from redis

# Automatically added by dh_installinit
if [ -x "/etc/init.d/relevanced" ]; then
    invoke-rc.d relevanced stop || exit $?
fi
# End automatically added section
